apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: gitee-v8-token-secret
  namespace: gitee-v8-token
spec:
  keysMap:
    access_key_id:
      key: access_key_id
      path: secrets/data/mindspore/gitee-v8-token
    obs_bucketname:
      key: obs_bucketname
      path: secrets/data/mindspore/gitee-v8-token
    obs_endpoint:
      key: obs_endpoint
      path: secrets/data/mindspore/gitee-v8-token
    obs_object_key:
      key: obs_object_key
      path: secrets/data/mindspore/gitee-v8-token
    query_token:
      key: query_token
      path: secrets/data/mindspore/gitee-v8-token
    secret_access_key:
      key: secret_access_key
      path: secrets/data/mindspore/gitee-v8-token
    secret_key:
      key: secret_key
      path: secrets/data/mindspore/gitee-v8-token
  name: gitee-v8-token-secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: invite-enterprise-members-secret
  namespace: gitee-v8-token
spec:
  name: invite-enterprise-members-secret
  keysMap:
    v8url:
      key: v8url
      path: secrets/data/mindspore/invite-enterprise-members
    query_token:
      key: query_token
      path: secrets/data/mindspore/invite-enterprise-members
    inviteapiurl:
      key: inviteapiurl
      path: secrets/data/mindspore/invite-enterprise-members
    roleid:
      key: roleid
      path: secrets/data/mindspore/invite-enterprise-members
    updatefileapiurl:
      key: updatefileapiurl
      path: secrets/data/mindspore/invite-enterprise-members
    faqfilename:
      key: faqfilename
      path: secrets/data/mindspore/invite-enterprise-members
    accesstoken:
      key: accesstoken
      path: secrets/data/mindspore/invite-enterprise-members
