resources:
- namespace.yaml
- secret.yaml
- message-server
- hook-delivery
- hook-dispatcher
- access
- sync-repo
- training-center-huaweicloud
- xihe-website
- xihe-server
namespace: xihe-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
