apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    training_endpoint: http://service-training-center-huaweicloud.xihe-new.svc.cluster.local:8888/api/v1/training
    mongodb:
      db_conn: "${MONGODB_CONNECTION}"
      db_name: "${MONGODB_NAME}"
      collections:
        project: project
        model: model
        dataset: dataset 
        user: user
        login: login
        like: like
        activity: activity
        tag: tag
        luojia: luojia
        training: training
        evaluate: evaluate
        inference: inference
        aiquestion: aiquestion
        competition: competition

    domain:
      min_name_length: 3
      max_name_length: 35
      max_desc_length: 200
      min_training_name_length: 1
      max_training_name_length: 64
      max_training_desc_length: 256
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache-2.0"
      - "mit"
      - "cc-by-sa-3.0"
      - "afl-3.0"
      - "cc-by-sa-4.0"
      - "lgpl-3.0"
      - "lgpl-lr"
      - "cc-by-nc-3.0"
      - "bsd-2-clause"
      - "ecl-2.0"
      - "cc-by-nc-sa-4.0"
      - "cc-by-nc-4.0"
      - "gpl-3.0"
      - "cc0-1.0"
      - "cc"
      - "bsd-3-clause"
      - "agpl-3.0"
      - "wtfpl"
      - "artistic-2.0"
      - "postgresql"
      - "gpl-2.0"
      - "isc"
      - "eupl-1.1"
      - "pddl"
      - "bsd-3-clause-clear"
      - "mpl-2.0"
      - "odbl-1.0"
      - "cc-by-4.0"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

    mq:
      address: "${KAFKA_ADDRESS}"
      topics:
        fork: "xihe_fork_new"
        like: "xihe_like_new"
        evaluate: "xihe_evaluate_new"
        training: "xihe_training_new"
        inference: "xihe_inference_new"
        following: "xihe_following_new"
        submission: "xihe_submission_new"
        related_resource: "xihe_related_resource_new"

    evaluate:
      endpoint: http://service-inference-evaluate.xihe-new.svc.cluster.local:8888
      survival_time: 10800

    inference:
      endpoint: http://service-inference-evaluate.xihe-new.svc.cluster.local:8888
