apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    inference: 
      rpc_endpiont: service-internal-server.xihe-new.svc.cluster.local:8888
      gitlab_endpiont: "${GITLAB_HOST}"
      obs:
        access_key: "${HW_OBS_AK}"
        secret_key: "${HW_OBS_SK}"
        endpoint: "${HW_OBS_ENDPOINT}"
        bucket: "${HW_OBS_BUCKET}"
        obsutil_path: /usr/src/app/obsutil
        lfs_path: gitlab-lfs
      crd:
        crd_image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate:inferenceimpl.v1.0.20221126115653
        crd_cpu: 0.5
        crd_memory: 512
        crd_template: /opt/app/template/crd-inference.yaml

    evaluate:
      rpc_endpiont: service-internal-server.xihe-new.svc.cluster.local:8888
      crd:
        crd_image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate:evaluateimpl.v1.0.20221124180204
        crd_cpu: 0.5
        crd_memory: 512
        crd_template: /opt/app/template/crd-evaluate.yaml

    k8s:
      kind: CodeServer
      group: cs.opensourceways.com
      version: v1alpha1
      namespace: mindspore-xihe-new
      kube_config_file: /app/conf/xihe-gitlab/kube/config
