apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config:
      watching_files:
        org: oepkgs
        repo: oepkgs-management
        branch: master
        repo_org: echo-oepkgs
        sig_file_path: sig/sigs.yaml
        sig_dir: sig
      concurrent_size: 50
      interval: 3
      obs_meta_project:
        obs_repo:
          org: oepkgs
          repo: testrelease-management
          branch: master
        project_dir: master/openEuler-Factory
        project_file_name: pckg-mgmt.yaml

