---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: xihe-tls
  namespace: xihe-test-v2
spec:
  name: xihe-tls
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/xihe-test-v2
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/xihe-test-v2
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/xihe-test-v2
      key: server.key
