---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/mindspore/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/mindspore/mail_secrets
      key: secret_key
    postgres_user:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_user
    postgres_password:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_password
    mailman_admin_email:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_admin_email
    exim4_credential:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential
    exim4_credential_username:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_password:
      path: secrets/data/mindspore/mail_secrets
      key: exim4_credential_splitted_password
    dkim_key:
      path: secrets/data/mindspore/mail_secrets
      key: dkim_key
    mailweb_smtp_host:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_smtp_host
    mailweb_smtp_port:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_smtp_port
    mailweb_django_allowed_hosts:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_django_allowed_hosts
    mailweb_postorius_template_base_url:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_postorius_template_base_url
    mailweb_database_url:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_database_url
    mailcore_mm_hostname:
      path: secrets/data/mindspore/mail_secrets
      key: mailcore_mm_hostname
    mailcore_rest_port:
      path: secrets/data/mindspore/mail_secrets
      key: mailcore_rest_port
    mailcore_database_url:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_database_url
    mailcore_mta:
      path: secrets/data/mindspore/mail_secrets
      key: mailcore_mta
    mailcore_smtp_port:
      path: secrets/data/mindspore/mail_secrets
      key: mailweb_smtp_port
    database_type:
      path: secrets/data/mindspore/mail_secrets
      key: database_type
    database_class:
      path: secrets/data/mindspore/mail_secrets
      key: database_class

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets
  namespace: mail
spec:
  name: mailman-cert-secrets
  keysMap:
    server_crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    server_key:
      path: secrets/data/mindspore/website-secrets
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-tls-secrets
  namespace: mail
spec:
  name: mailman-tls-secrets
  keysMap:
    mindspore_cn_crt:
      path: secrets/data/mindspore/mail_secrets
      key: mindspore_cn_crt
    mindspore_cn_key:
      path: secrets/data/mindspore/mail_secrets
      key: mindspore_cn_key