# Config web service
---
apiVersion: v1
kind: Service
metadata:
  name: mailman-web-service
  namespace: mail
spec:
  ports:
  - port: 8000
    name: website-port-uwsgi-http
    targetPort: 8000
    protocol: TCP
  - port: 80
    name: website-port-http
    targetPort: 80
    protocol: TCP
  selector:
    component: mail-web-service
  type: ClusterIP

# Deployment for mail web service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mailman-web
  namespace: mail
  labels:
    component: mail-web-service
    app: mail-suit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mail-web-service
      app: mail-suit-service
  template:
    metadata:
      labels:
        component: mail-web-service
        app: mail-suit-service
    spec:
      hostname: mailman-web
      containers:
        - name: mailman-web
          # We modified the mail-web image to add static folder.
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-web-new-build:291336826605a3042b214075bb9037a52f97058c1673252910
          imagePullPolicy: "Always"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
          env:
            - name: PRIVACY_LINK
              value: https://mindspore.cn/privacy/en/
            - name: CONDUCT_LINK
              value: https://gitee.com/mindspore/community/blob/master/code-of-conduct_en.md
            - name: DATABASE_TYPE
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: database_type
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: hyperkitty_api_key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: secret_key
            - name: MAILMAN_REST_URL
              value: http://mailman-core-0.mail-suit-service.mail.svc.cluster.local:8001
            - name: MAILMAN_HOST_IP
              value: mailman-core-0.mail-suit-service.mail.svc.cluster.local
            - name: MAILMAN_ADMIN_USER
              value: mindspore
            - name: MAILMAN_REST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_user
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_password
            - name: MAILMAN_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_admin_email
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_username
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_password
            #NOTE: this is the domain name that mailman web will serve
            - name: SERVE_FROM_DOMAIN
              value: mailweb.mindspore.cn
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailweb_smtp_host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailweb_smtp_port
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailweb_django_allowed_hosts
            - name: POSTORIUS_TEMPLATE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailweb_postorius_template_base_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailweb_database_url
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 2000m
              memory: 4000Mi
          volumeMounts:
            - mountPath: /opt/mailman-web-static
              name: mailman-web-volume
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx-web
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: mailman-nginx-configmap-volume
            subPath: nginx.conf
          - mountPath: /etc/nginx/conf.d/default.conf
            name: mailman-nginx-configmap-volume
            subPath: default.conf
          - mountPath: /opt/mailman-web-static
            name: mailman-web-volume  
      volumes:
        - name: mailman-web-volume
          emptyDir: {}
        - name: mailman-nginx-configmap-volume
          configMap:
            name: mailman-nginx-configmap
