apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- secrets_nlp.yaml
- oepkgs-review
- oepkgs-welcome
- repo-watcher-oepkgs
- repo-watcher-src-oepkgs
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee-oepkgs
