resources:
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
namespace: helios-server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/helios-server/helios-voting
  newTag: master-545cf1e
