apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: helios-server-secret
  namespace: helios-server
spec:
  name: helios-server-secret
  keysMap:
    GH_CLIENT_ID: &id001
      key: EMAIL_HOST_PASSWORD
      path: secrets/data/mindspore/helios-server
    GH_CLIENT_SECRET: *id001
    GOOGLE_CLIENT_ID: *id001
    GOOGLE_CLIENT_SECRET: *id001
    GITEE_CLIENT_ID: *id001
    GITEE_CLIENT_SECRET: *id001
    DB_HOST: *id001
    DB_PORT: *id001
    DB_USER: *id001
    DB_PASSWORD: *id001
    EMAIL_HOST: *id001
    EMAIL_PORT: *id001
    EMAIL_HOST_USER: *id001
    EMAIL_HOST_PASSWORD: *id001
