apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: access
        args:
        - --port=8888
        - --config-file=/app/conf/xihe-gitlab/app_config/config.yaml
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-gitlab:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/xihe-gitlab/app_config/
          name: app-config
          readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: configmap-access
